### ISSUE TITLE
Complete TranslationModelConfiguration

### ISSUE THREAD

**Issue by jerinphilip** [browsermt/bergamot-translator#11]
If `TranslationModelConfiguration` needs to be kept, I suggest we write `Options` (service-cli) -> `TranslationModelConfiguration` -> Options and then init Service with the `Options` to to check if `TranslationModelConfiguration` is comprehensive enough to cover the configuration required to build the model.  

I must say I am of the opinion not to be re-implementing `Options` capability inside `TranslationModelConfiguration`, but if this is a hard requirement somebody needs to do this.

@abhi-agg: Consider this a self-assigned todo? https://github.com/browsermt/bergamot-translator/blob/fd897dc4ec551958d973cdc8a55bb003bc343884/src/translator/TranslationModelConfigToOptionsAdaptor.cpp#L15

**Comment by abhi-agg** [comment]
I am fine with removing `TranslationModelConfiguration`.

However, having YAML::Node in the interface will force us to include yaml specific header files in the interface. I propose this instead:

```
std::shared_ptr<AbstractTranslationModel>
AbstractTranslationModel::createInstance(const std::string& configString)

```
where `configString` would be a Yaml-formatted string (it can be a Json-formatted string too as YAML parser can parse both formats).
We can then use YAML parser internally to create YAML::Node (or marian::Options) from `configString`.

Few things to note:
1. The user of the API will not be forced to explicitly provide all optional config options or the config options that user doesn't want to override in `configString`. e.g. If user doesn't provide "num-devices" in `configString` then the inference should run with whatever default value marian has for "num-devices".
2. We need a good documentation of these options. e.g. The [actual config options](https://github.com/browsermt/marian-dev/blob/master/src/common/config_parser.cpp) are more than what is specified in the [documentation](https://marian-nmt.github.io/docs/cmd/marian-decoder/).

**Comment by abhi-agg** [comment]
Submitted a PR for this: https://github.com/browsermt/bergamot-translator/pull/15

**Comment by motin** [comment]
Throwing this in here since it is on the subject of completing TranslationModelConfiguration. I am not up to speed on the bleeding edge considerations - so pardon my ignorance: I am happy regarding v1 as long as translation as per https://github.com/browsermt/students/blob/9ce4409c00a4802f3819cfe1a70e6b720db142bd/esen/esen.student.tiny11/speed.cpu.intgemm8bitalpha.sh#L27-L33 is possible. It seems like many of those cli parameters are irrelevant in the API context (logging, output modification etc), but ideally it should be possible to play around with different batch sizes, and critically I don't see the lexical shortlist being configurable in the current draft implementation.

**Comment by abhi-agg** [comment]
@motin We have reached an agreement on this topic. According to the new proposal, all the configurations which are possible for marian translator can be provided by the consumer of the APIs in form of yaml-formatted string (instead of `TranslationModelConfiguration` class). So, no worries on this front.

So, we will be able to experiment with everything.
