### ISSUE TITLE
Testing / CD meta issue

### ISSUE THREAD

**Issue by jerinphilip** [browsermt/bergamot-translator#119]
1. ~~Collapse x and x-bytearray apps into one through a command line flag. There's a lot of redundancy in the printing code for both and stuff is requiring edits in both places. (#120)~~
2. (In Progress: #184) There's one output app where outputs for all features are bound to regression tests. I would prefer to break this down to feature level so edits are not all over the place while we parallelize development which affects each of these features:
    a. source text -> translated text
    b. source sentence mappings -> translated sentence-mappings (checking sentence alignments)
    c. quality
    d. alignments
3. BRT is bound to hardware / instructions available. This is not pleasant as generation and moving around when code is updated to change output is a lot of manual labour at the moment. Once there are 4 x #instructions (ssse3, avx, avx2, avx512, avx512vnni = 5 at the moment) is a lot of files to store as expected ground truths. Something needs to change here so things can be automated. https://github.com/kpu/intgemm/issues/84 this can solve part of the issue. Nick describes this also being a function of the compiler and BLAS supplied.
4. As of now we're testing code here with only the en -> de pipeline. For purposes of a model zoo (which I'm guessing is the ideal direction), it's best if we generalize this for other language directions and changes in models should also trigger errors in regression tests if something fails (https://github.com/browsermt/students or https://github.com/mozilla-applied-ml/bergamot-models).

**Comment by XapaJIaMnu** [comment]
As to point 2)
I think a simple sentence mapping a BLEU score with some tolerance of 0.1 would probably work just as well to detect breakage.

As to point 3)
1. Floating point precision issues. When adding/mutliplying floating point numbers the results may vary based on the compiler used/OS used/library version used/CPU hardware used. Currently all of our models go through a BLAS provider (AppleAccelerate/MKL/OpenBLAS). We have ssse3-avx512vnni architectures and I know of no reliable way to limit the instruction generation to be only of specific range (eg up to ssse3) when linking with the libraries, because they do runtime CPU detection and have dedicated codepaths for various architectures. Some flags exist, eg:
```
MKL_ENABLE_INSTRUCTIONS=SSE4_2
MKL_ENABLE_INSTRUCTIONS=AVX
MKL_ENABLE_INSTRUCTIONS=AVX2
MKL_ENABLE_INSTRUCTIONS=AVX512
```
But I am not sure if SSE4_2 MKL codepath would produce the same result on a very old processor, as well as on a very new processor (BUT IT MAY HELP).
2. Saturation issues. Pre AVX512VNNI 8bit integer gemm operations could overflow depending on the order in which the multiply-add instruction adds the numbers. The order is undefined and may vary with architecture, so limiting the ARCH by flag is also not guaranteed to produce consistent results across architectures (BUT MAY HELP).

as to point 4, we only need to test one model for a single language. I don't see any way in which the performance of just one model would regress but the rest would stay constant.

**Comment by jerinphilip** [comment]
So in #127, I'm about to fix the tests as well including Mac, disabling accelerate. But the problem I am facing is just of precision. I'm looking also at decomposing outputs as I mentioned in 2. I want to also output it in a structured consumable format where I can parse and compare with a defined tolerance in precision. I'd also prefer the outputs to be readable.

I'm thinking of having JSON as output, which are parsed, and will therefore add a json dependency. This JSON or whatever is the format can potentially be reused in a REST server or some messaging:

a. `<arch>/text.{out,expected}.json`
b. `<arch>/sentences.{out,expected}.json`
c. `<arch>/alignment.{out,expected}.json`
d. `<arch>/quality.{out,expected}.json`

The above will also allow independent tests and reports of success / failure on each feature, allowing quality people to perhaps just focus on (d).

Any foreseeable issues @XapaJIaMnu, @kpu? Can I go forward with this?

**Comment by jerinphilip** [comment]
There are still the following variations which create a matrix.

1. Intgemm on some matrices, attention matrices being MKL or something. The MKL bit creates variations.
2. Compiler version differences also lead to minor issues.

This is nearly unsolvable and not worth the time and effort, an approximate option during BRTs is checked in for anyone who wants to quickly check if it's not a quality issue but a floating point issue.

```
... BRT_EVAL_MODE="approx" ./run_brt.sh ....
```

In approximate mode, outputs fall back to avx512vnni generated on var (but the texts and numbers are compared with tolerances).
