### ISSUE TITLE
Multiple Translation models

### ISSUE THREAD

**Issue by jerinphilip** [browsermt/bergamot-translator#209]
We're going for solving support from the translator side for outbound translation models (#78) treating this as a multiple translation models solution (Not just forward and backward models, possibly more than 2).

Based on the discussions I've had with @kpu, the following planned design will not be backward compatible due to now additionally requiring information on which model to use for each translate calls. 

The entities that are involved in the translation of a single direction will be abstracted together and separated from the translation process (which is effectively going to be reduced to a thread pool after).

The following components are associated with the translation of a single direction

* Marian Model
* TextProcessor: [Vocabularies, SentenceSplitter]
* ShortList
* Ordered-by-Length-storage for Batch Generation (to generate homogeneous w.r.t single-direction batches)
* QualityEstimator (*under development; @abarbosa94 @mfomicheva @felipesantosk)

Consequently the above will be packed together in a single class, which @kpu prefers to call a `TranslationModel` (https://github.com/browsermt/bergamot-translator/issues/149#issuecomment-842309639).

The following could be shared among the `TranslationModel`s that are active:

* A thread pool of workers to produce batches from batch pools and translate (consume). 
* Translation-Cache (*under development, @jerinphilip)

`Service` will change to additionally accepting a reference to a `TranslationModel` instance in the `translate(...)` API to provide model information. `Service`, `BatchTranslator` will be cut and moved into `TranslationModel` and `Service`. `BatchTranslator` will in all likelihood, cease to exist with data going to `TranslationModel` and methods ~~moving into `Service`~~ becoming free functions.

Note that in this design, the API user (WASM+JS; @abhi-agg or translateLocally; @XapaJIaMnu ) is expected to own and manage `TranslationModel`s. Ownership will have to be shared while the translation process in other threads is active, so expect some `shared_ptr<TranslationModel>` floating around.

The interaction of producing batches and clearing out orphan sentences when a model is deleted among several `TranslationModel`s is a fuzzy area w.r.t ownership (at least to me). I will possibly have a clearer picture once I try out the implementation, look into the nuances. We may end up taking up managing models if clearing out orphan batch/sentences/models get unnecessarily tricky.

**Comment by jerinphilip** [comment]
The draft now successfully demonstrates the intended feature, by allowing for `TranslationModel` to be kept separately and supplied during translation.

As far as an external client/user is concerned, the following are the changes:

```cpp
// NEW: Create model, or models with options (alternatively std::string config)
// This holds the data etc required for translation in one direction.
std::shared_ptr<TranslationModel> 
	model = std::make_shared<TranslationModel>(options, std::move(memoryBundle));
	
// Blocking code / async through a thread-pool which abstracts the translation mechanism.
Service service(options);

// In async workflow:
service.translate(model, std::move(source), callback, responseOptions);
//                ^ NEW: Supply model as parameter

// In blocking workflow, for WASM Client
std::vector<Response> 
	responses = service.translateMultiple(model, std::move(texts), responseOptions);
//                                         ^ NEW: Supply model as parameter
```

Evident from above, once `std::shared_ptr<TranslationModel>` is available in JS, JS can inventory and swap available models as demanded by the situation. For example, inventory will have a "forward" `xx -> yy` model for normal surfing and a "backward" `yy -> xx` model for outbound translation either of which can be supplied depending on what's needed. 

I will proceed to polish the PR preparing it for review. 

* @abhi-agg: If there are any comments on this API restructure / design, particularly any conflicts w.r.t web assembly + JS compatibility and that sort in the newly brought forward structures please let me know in this thread. 
* WASM Bindings are in the way with CIs red. I will try to edit bindings and get the code to compile and get it to green, however, I will not be testing if it works or not (in JS land, that is).

**Comment by abhi-agg** [comment]
@jerinphilip I was going through the PR https://github.com/browsermt/bergamot-translator/pull/210 and I have few questions:

1. Do we really need to return an instance of `TranslationModel` from `BlockingService` (or even the `AsyncService`) class? Instead, can't we just return a unique id that represents a TranslationModel instance to the user? The user can just pass this unique id instead of TranslationModel. The Service classes can maintain a map of unique ids to TranslationModel instances internally. This will keep the interface clean and minimal. Something like this (left irrelevant parts in the code):
    ```c++
    class BlockingService {
    public:
        using UniqueId = uint32_t;
    
        BlockingService() : id_(0), requestId_(0), batchingPool_() {}

        template <class ConfigType>
        UniqueId createCompatibleModel(const ConfigType &config, MemoryBundle &&memory) {
            // generate a unique id for the translation model (a super simple method would be: id_++)
            UniqueId unique_id = generateUniqueId(id_);
            map.insert(unique_id, New<TranslationModel>(config, /*replicas=*/1, std::move(memory));
            return unique_id;
        }

        std::vector<Response>
        translateMultiple(UniqueId modelUniqueId, std::vector<std::string> &&source, const ResponseOptions &responseOptions) {
            // Get the TranslationModel corresponding to modelUniqueId from map
            shared_ptr<TranslationModel> model = map_id_to_translationmodel_[modelUniqueId]
            // work with model hereafter
            ...
            ...
        }

    private:
        size_t                  requestId_;
        AggregateBatchingPool   batchingPool_;
        UniqueId                id_;  // A unique id that represents the TranslationModel instance in the map below
        std::map<UniqueId, shared_ptr<TranslationModel>>     map_id_to_translationmodel_;
    }
    ```
    In my opinion, user doesn't really need the `TranslationModel` instance at its end. Exposing this will also require generating JS bindings for TranslationModel class which seems to be additional overhead.
    
    The code for the client will look like this (taking only blocking service as example):

    ```c++
    // Blocking code which abstracts the translation mechanism
    BlockingService service;

    // NEW: Create model, or models with options and get the unique ids
    uint32_t model_id1 = service.createCompatibleModel(options1, std::move(memoryBundle1));
    uint32_t model_id2 = service.createCompatibleModel(options2, std::move(memoryBundle2));
    ...
    ...
	
    // Translate call
    std::vector<Response> responses1 = service.translateMultiple(model_id1, std::move(texts), responseOptions1);
    std::vector<Response> responses2 = service.translateMultiple(model_id2, std::move(texts), responseOptions2);

    ```


    Please let me know if I miss something here 👍 

2. It seems to me that we have removed `WASM_COMPATIBLE_SOURCE` from the bergamot code base. This directive was enabling us to compile bergamot to Wasm without any thread related code. Can we still compile bergamot to wasm without any thread related sources?

**Comment by jerinphilip** [comment]
> 1. The Service classes can maintain a map of unique ids to TranslationModel instances internally. This will keep the interface clean and minimal.

Copying @kpu, I had asked this (the question was whether we take up model management or not) before implementation and was advised against it - I'm sure there should be good reasons. 

Your suggestion has a memory leak, at least based on the current description. Could you kindly detail how the life-cycle of a `TranslationModel` is handled/controlled in your approach?

> ... Exposing this will also require generating JS bindings for TranslationModel class which seems to be additional overhead.

Where/What exactly is the "additional overhead"? Some details? References to documentation?

> 2. ...Can we still compile bergamot to wasm without any thread related sources?

CI which is setup for WASM is compiling, which I had to get green, and I have. We are compiling bergamot to wasm "with" thread-related sources "successfully", therefore. As for the original question - I don't know.

**Comment by abhi-agg** [comment]
> > 1. The Service classes can maintain a map of unique ids to TranslationModel instances internally. This will keep the interface clean and minimal.
> 
> Copying @kpu, I had asked this (the question was whether we take up model management or not) before implementation and was advised against it - I'm sure there should be good reasons.

It would be interesting to know these reasons. In its current state, the other APIs of `TranslationModel` class (e.g. `generateBatch`, `translateBatch`, `makeRequest` etc.) seem to be working as a backend for the Service classes. May be, I am missing something here 👍

> Your suggestion has a memory leak, at least based on the current description. Could you kindly detail how the life-cycle of a `TranslationModel` is handled/controlled in your approach?

If you are referring to the memory leak of the `TranslationModel` instance then it is very straight forward. Service classes can provide an API which will destruct the TranslationModel instance. So something like:

`void BlockingService::destructModel(UniqueId id);`

The responsibility of destruction still lies in the hands of the user (which is also the case in your current proposal).

Please let me know if you are referring to some other memory leak here.

> > ... Exposing this will also require generating JS bindings for TranslationModel class which seems to be additional overhead.
> 
> Where/What exactly is the "additional overhead"? Some details? References to documentation?

I am talking about the additional overhead of the JS bindings code. This code will be generated just because we want the user to create `TranslationModel` instance to be able to use the Service class.

> > 1. ...Can we still compile bergamot to wasm without any thread related sources?
> 
> CI which is setup for WASM is compiling, which I had to get green, and I have. We are compiling bergamot to wasm "with" thread-related sources "successfully", therefore. As for the original question - I don't know.

Tagging @lonnen and @andrenatal here. If we loose the existing capability to compile bergamot without any thread related sources then the JS code will start using Shared Array Buffer and it will have to be enabled in browsers for the extensions to work.

**Comment by kpu** [comment]
@abhi-agg This is C++ with constructors and destructors.  Resource allocation is initialization.  

Here a resource, namely a translation model, is being allocated.  So you get a class that represents this allocation whose destructor corresponds to freeing the model.  Though here we are using a shared pointer because there may still be threads working on the translation at the time you consider it no longer necessary.  

A `size_t` handle with an explicit non-standard means of destruction is not using C++ properly.  And it breaks the best practice of explicitly holding resources via an object with a destructor.  

You will get a class from us with a proper destructor.  Should you wish to break this best practice, you can do so in your own binding code.

**Comment by abhi-agg** [comment]
Great. So this one is resolved.

The only thing left to be done is to rebase the PR and adapt it to fix CI failures (wasm compilation without thread sources).

@jerinphilip Please let me know when the code is ready from your side. I will then test it on JS side and we can merge it then.

**Comment by kpu** [comment]
This all said, were the design to look like:
```
class TranslationModel {
  public:
    TranslationModel(Service &service, const std::string &config, MemoryBundle memoryBundle = {});
    // More stuff here.
};
```
Then @abhi-agg can just do `new TranslationModel(service, config, memoryBundle)` and the pointer can be his desired untracked memory.
